import Head from "next/head";
import Image from "next/image";
import landingImg from "../../public/logo_landing.png";
import { useState } from "react";
import Login from "../components/Login/Login";
import Register from "../components/Register/Register";
import PersonAddAltIcon from "@mui/icons-material/PersonAddAlt";
import InputIcon from "@mui/icons-material/Input";
import { UserAuth } from "@/context/AuthContext";
import CircularIndeterminate from "@/components/Loader/Loader";

export default function Home() {
  const { user } = UserAuth();

  const [login, setLogin] = useState<boolean>(true);
  const [loading, setLoading] = useState<boolean>(false);

  function handleLoginClick() {
    setTimeout(() => {
      setLogin(!login);
    }, 100);
  }

  return (
    <>
      <Head>
        <title>NEXBOARD</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="landing-container">
          <div className="landing-left-wrapper">
            {login ? (
              <Login setLoading={setLoading} />
            ) : (
              <Register setLoading={setLoading} />
            )}
          </div>
          {!loading && <div className="landing-right-wrapper">
            <Image src={landingImg} width={650} height={500} alt="" priority />
            {!login ? (
              <span className="icon-wrapper">
                <InputIcon className="icon" onClick={handleLoginClick} />
                <p>Login</p>
              </span>
            ) : (
              <span className="icon-wrapper">
                <PersonAddAltIcon className="icon" onClick={handleLoginClick} />
                <p>Registracija</p>
              </span>
            )}
          </div>}
          {loading && <CircularIndeterminate />}
        </div>
      </main>
    </>
  );
}
